# Generated by Django 4.1.4 on 2022-12-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='employee_id',
            new_name='eid',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='employee',
            new_name='name',
        ),
    ]
